Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(train.py:4587): Gdk-CRITICAL **: 10:53:34.289: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "scripts/train_cifar/train.py", line 22, in <module>
    from lib.mli_eval.plotting.interp import plot_interp
  File "/usr/xtmp/CSPlus/VOLDNN/Annie/mli-release/lib/mli_eval/plotting/interp.py", line 7, in <module>
    import lib.mli.metrics as metrics_utils
ModuleNotFoundError: No module named 'mli'
